### ISSUE TITLE
궁금한게 하나 있습니다!

### ISSUE THREAD

**Issue by Kwonkunkun** [Kwon-Bum-Kyu/react-native-tmap-navi#1]
안녕하세요! 
현재 프로덕트 코드와 묶여있는 bridge module을 따로 빼서 npm에 올려놓고 프로덕트에서 가져오고 싶어 [react awsome module](https://github.com/callstack/react-native-builder-bob) 을 이용해서 시도하고 있습니다.

**시도 방식**
tmap sdk는 pod에 따로 올라와있지 않아 pod spec의 vendored_frameworks 옵션을 이용해서 framework를 만들고 있는 모듈에 추가해서 개발하는 방식으로 하고있는데

**문제**
근데 이렇게 하게 되니 ios는 빌드시에 header를 찾지를 못하더라구요. 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/59603575/201462249-90a186f9-2bbf-43b6-8b63-8c67c730d969.png">
여러 서칭을 해보았으나.. 유의미한 결과를 얻지는 못했습니다. 

**궁금한점**
범규님의 코드를 보니 따로 sdk를  빼놓고 podspec에 dependency를 걸어둔거 같아서요. 어떤방식으로 한건지 궁금해서 글 올립니다.

**Comment by Kwonkunkun** [comment]
아 천천히 다시 살펴보니 빌드시에 header를 찾지 못하는 문제는.. 제가 잘못한거였네요ㅠ

**Comment by Kwon-Bum-Kyu** [comment]
네 안녕하세요 @Kwonkunkun 님! 문제는 잘 해결되셔서 다행이네요!
저도 건드린지 오래된 부분이라 정확하게 기억은 못하지만 SDK를 따로 분리해두었던 이유는 iOS에 대한 지식이 부족하다보니 SDK에 대한 자료를 찾아서 dependency에 걸어두는 방식으로 활용했었습니다. [reference Link](https://github.com/Kwon-Bum-Kyu/react-native-tmap-navi#reference-link)해당 부분에서 자료를 만들때 활용했던 링크들이 걸려있으니 이 부분을 확인해보셔도 좋을거 같아요!

**Comment by Kwonkunkun** [comment]
답변 감사합니다!
